name: pFootcube
version: 1.1
description: Footblal in minecraft.
author: czhixsy
main: me.czhixsy.footcube.FootCube
commands:
  cube:
    description: Stvara loptu.
  clearCubes:
    description: Brise sve lopte.
  clearCube:
    description: Brise najblizu loptu
  tc:
    description: Timski Cet
  footcube:
    aliases: [pfc]
    description: Glavna komanda plugina.
  commandDisabler:
    aliases: [cd]
    description: Dozvoliti Onemoguciti komande tokom meca..
  spy:
    description: Dozvoliti Onemoguciti Spijniranje
  g:
    description: Globalni Cet
