name: pFootcube
version: 1.1
description: Footblal in minecraft.
author: czhixsy
main: me.SmileyCraft.footcube.FootCube
commands:
  cube:
    description: spawns a ball
  clearCubes:
    description: removes all cubes
  clearCube:
    description: removes nearest cube
  tc:
    description: team-chat
  footcube:
    aliases: [fc]
    description: main plugin command
  commandDisabler:
    aliases: [cd]
    description: enable / disable commands in a match
  spy:
    description: enable / disable spying
  g:
    description: global ch
